apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: student-mgmt-system
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: changeme-root-password   # replace / manage via AWS Secrets Manager in prod
  MYSQL_DATABASE: studentdb
  MYSQL_USER: sms_app
  MYSQL_PASSWORD: changeme-app-password
